version: "3.9"

services:

  java-backend:
    build: .
    container_name: sintonya-backend
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/var/uploads
#    volumes:
#      - ./uploads:/var/uploads

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: sintonya-rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: sintonya_user
#      RABBITMQ_DEFAULT_PASS: sintonya_pass
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq
#    networks:
#      - monitoring
#
#volumes:
#  pgdata:
#  dbeaver-data:
#  pgadmin-data:
#  rabbitmq-data:
#  n8n-data: