version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sintonya-postgres
    environment:
      POSTGRES_DB: sintonya_db
      POSTGRES_USER: sintonya_user
      POSTGRES_PASSWORD: sintonya_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - sintonya-network

  dbeaver:
    image: dbeaver/cloudbeaver
    container_name: sintonya-dbeaver
    ports:
      - "8978:8978"
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      - postgres
    networks:
      - sintonya-network

  java-backend:
    build: .
    container_name: sintonya-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sintonya_db
      SPRING_DATASOURCE_USERNAME: sintonya_user
      SPRING_DATASOURCE_PASSWORD: sintonya_pass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - sintonya-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: sintonya-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: sintonya_user
      RABBITMQ_DEFAULT_PASS: sintonya_pass
    ports:
      - "5672:5672"   # porta usada pelas aplicações (Spring, etc)
      - "15672:15672" # painel web do RabbitMQ
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - sintonya-network

volumes:
  pgdata:
  dbeaver-data:
  rabbitmq-data:

networks:
  sintonya-network:
    external: true