package com.example.demo.enums;

public enum EnumPermissions {
    PROFILE_UPDATE,
    SKILL_ADD,
    SKILL_UPDATE,
    CERTIFICATE_CREATE,
    CERTIFICATE_UPDATE,
    CERTIFICATE_DELETE,
    EXPERIENCE_CREATE,
    EXPERIENCE_UPDATE,
    EXPERIENCE_DELETE,
    VACANCY_VIEW,
    VACANCY_APPLY,
    VACANCY_CREATE,
    VACANCY_UPDATE,
    VACANCY_CLOSE,
    CANDIDATE_VIEW,
    ENTERPRISE_VIEW,
    ADMIN_ACCESS
}
