spring.application.name=sintonya

# ===============================
# DATABASE - POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.yostjyqvdofdqteavwwb
spring.datasource.password=ab123456523dddf
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000

supabase.url=https://yostjyqvdofdqteavwwb.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvc3RqeXF2ZG9mZHF0ZWF2d3diIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjA5NzQ4MCwiZXhwIjoyMDkxNjczNDgwfQ.CJZU1U6IPDt1dFIFQl4OZd6fxN12_F6gLISrT-z5sSQ
supabase.bucket=storage

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.address=0.0.0.0
server.port=8080

# ===============================
# H2 CONSOLE (DESABILITADO)
# ===============================
spring.h2.console.enabled=false

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=sintonya_user
spring.rabbitmq.password=sintonya_pass

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.web.server.auto-time-requests=true
management.metrics.enable.all=true


otel.logs.exporter=none
otel.service.name=sintonya
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.exporter.otlp.endpoint=http://otel-collector:4317
otel.exporter.otlp.protocol=grpc

app.upload.dir=/var/uploads


