--
-- PostgreSQL database dump
--

\restrict kGWHK2nj6pumHsEYunCa2zAuxEb6JwiZkUDlNte1gNR4WL8D0V89BvXgDR2hDzC

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: increment_workflow_version(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.increment_workflow_version() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
			BEGIN
				IF NEW."versionCounter" IS NOT DISTINCT FROM OLD."versionCounter" THEN
					NEW."versionCounter" = OLD."versionCounter" + 1;
				END IF;
				RETURN NEW;
			END;
			$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: application_analysis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_analysis (
    final_score double precision,
    id bigint NOT NULL,
    job_application_id bigint,
    compatibility_level character varying(255),
    final_feedback text
);


--
-- Name: application_analysis_dimension; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_analysis_dimension (
    score double precision,
    weight double precision,
    weighted_score double precision,
    analysis_id bigint,
    id bigint NOT NULL,
    selection_stage_id bigint
);


--
-- Name: application_analysis_dimension_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_analysis_dimension ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_analysis_dimension_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_analysis_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_analysis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_analysis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: application_stage_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_stage_result (
    locked boolean NOT NULL,
    score double precision,
    id bigint NOT NULL,
    job_application_id bigint,
    selection_stage_id bigint,
    stage_status character varying(255),
    CONSTRAINT application_stage_result_stage_status_check CHECK (((stage_status)::text = ANY ((ARRAY['LOCKED'::character varying, 'NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'PASSED'::character varying])::text[])))
);


--
-- Name: application_stage_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.application_stage_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.application_stage_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    candidate_id bigint,
    file_id bigint,
    id bigint NOT NULL,
    type character varying(255),
    CONSTRAINT attachments_type_check CHECK (((type)::text = ANY ((ARRAY['RESUME'::character varying, 'COVER_LETTER'::character varying, 'CERTIFICATE'::character varying, 'PORTFOLIO'::character varying])::text[])))
);


--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidate_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candidate_preferences (
    candidate_id bigint,
    id bigint NOT NULL,
    total_experience bigint,
    modality character varying(255),
    vacancy_type character varying(255),
    CONSTRAINT candidate_preferences_modality_check CHECK (((modality)::text = ANY ((ARRAY['ON_SITE'::character varying, 'REMOTE'::character varying, 'HYBRID'::character varying])::text[]))),
    CONSTRAINT candidate_preferences_vacancy_type_check CHECK (((vacancy_type)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'INTERSHIP'::character varying, 'TRAINEE'::character varying, 'TEMPORARY'::character varying, 'CONTRACT'::character varying, 'FREELANCE'::character varying, 'SELF_EMPLOYED'::character varying, 'VOLUNTEER'::character varying, 'APPRENTICESHIP'::character varying])::text[])))
);


--
-- Name: candidate_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.candidate_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidate_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candidates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candidates (
    date_of_birth date,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    profile_id bigint,
    sector_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    availability character varying(255),
    contact character varying(255) NOT NULL,
    cpf character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    gender character varying(255),
    race_ethnicity character varying(255),
    CONSTRAINT candidates_availability_check CHECK (((availability)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'INTERSHIP'::character varying, 'TRAINEE'::character varying, 'TEMPORARY'::character varying, 'CONTRACT'::character varying, 'FREELANCE'::character varying, 'SELF_EMPLOYED'::character varying, 'VOLUNTEER'::character varying, 'APPRENTICESHIP'::character varying])::text[])))
);


--
-- Name: candidates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.candidates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificate_sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.certificate_sectors (
    certificate_id bigint NOT NULL,
    sector_id bigint NOT NULL
);


--
-- Name: certificates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.certificates (
    expiration_date date,
    issue_date date,
    candidate_id bigint NOT NULL,
    hours bigint,
    id bigint NOT NULL,
    issuing_organization character varying(255),
    title character varying(255),
    url character varying(255)
);


--
-- Name: certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.certificates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enterprises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enterprises (
    is_approved boolean NOT NULL,
    size_enterprise smallint,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    number_of_employees bigint,
    profile_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    cnpj character varying(255) NOT NULL,
    contact character varying(255) NOT NULL,
    description character varying(255),
    enterprise_name character varying(255) NOT NULL,
    sector character varying(255),
    site_url character varying(255),
    social_reason character varying(255),
    CONSTRAINT enterprises_size_enterprise_check CHECK (((size_enterprise >= 0) AND (size_enterprise <= 2)))
);


--
-- Name: enterprises_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enterprises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enterprises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: experiences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.experiences (
    end_date date,
    is_current boolean NOT NULL,
    start_date date,
    candidate_id bigint,
    id bigint NOT NULL,
    description character varying(255),
    locality character varying(255),
    organization character varying(255),
    title character varying(255),
    work_modality character varying(255),
    work_type character varying(255),
    CONSTRAINT experiences_work_modality_check CHECK (((work_modality)::text = ANY ((ARRAY['ON_SITE'::character varying, 'REMOTE'::character varying, 'HYBRID'::character varying])::text[]))),
    CONSTRAINT experiences_work_type_check CHECK (((work_type)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'INTERSHIP'::character varying, 'TRAINEE'::character varying, 'TEMPORARY'::character varying, 'CONTRACT'::character varying, 'FREELANCE'::character varying, 'SELF_EMPLOYED'::character varying, 'VOLUNTEER'::character varying, 'APPRENTICESHIP'::character varying])::text[])))
);


--
-- Name: experiences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.experiences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.experiences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feed_item_score; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feed_item_score (
    score double precision,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: feed_item_score_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.feed_item_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feed_item_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id bigint NOT NULL,
    size bigint,
    content_type character varying(255),
    file_name character varying(255),
    media_type character varying(255),
    path character varying(255),
    CONSTRAINT files_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying])::text[])))
);


--
-- Name: files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: interaction; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interaction (
    id bigint NOT NULL,
    post_impression_id bigint
);


--
-- Name: interaction_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.interaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: job_application; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.job_application (
    candidate_id bigint NOT NULL,
    id bigint NOT NULL,
    vacancy_id bigint NOT NULL,
    status character varying(255),
    CONSTRAINT job_application_status_check CHECK (((status)::text = ANY ((ARRAY['APPLIED'::character varying, 'IN_PROGRESS'::character varying, 'WAITING_TEST'::character varying, 'TEST_IN_PROGRESS'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'WITHDRAW'::character varying])::text[])))
);


--
-- Name: job_application_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.job_application ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_application_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    permission_name character varying(255),
    CONSTRAINT permissions_permission_name_check CHECK (((permission_name)::text = ANY ((ARRAY['PROFILE_READ'::character varying, 'PROFILE_READ_BY_ID'::character varying, 'PROFILE_READ_DETAILS'::character varying, 'PROFILE_UPDATE'::character varying, 'CANDIDATE_READ'::character varying, 'CANDIDATE_READ_BY_ID'::character varying, 'CANDIDATE_READ_DETAILS'::character varying, 'ENTERPRISE_READ'::character varying, 'ENTERPRISE_READ_BY_ID'::character varying, 'ENTERPRISE_READ_DETAILS'::character varying, 'USER_READ'::character varying, 'USER_READ_BY_ID'::character varying, 'USER_READ_DETAILS'::character varying, 'VACANCY_READ'::character varying, 'VACANCY_READ_BY_ID'::character varying, 'VACANCY_READ_DETAILS'::character varying, 'VACANCY_CREATE'::character varying, 'VACANCY_UPDATE'::character varying, 'JOB_APPLICATION_READ'::character varying, 'JOB_APPLICATION_READ_BY_ID'::character varying, 'JOB_APPLICATION_READ_DETAILS'::character varying, 'JOB_APPLICATION_APPLY'::character varying, 'SELECTION_PROCESS_READ'::character varying, 'SELECTION_PROCESS_READ_BY_ID'::character varying, 'SELECTION_PROCESS_READ_DETAILS'::character varying, 'SKILL_READ'::character varying, 'SKILL_CREATE'::character varying, 'SKILL_UPDATE'::character varying, 'CERTIFICATE_READ'::character varying, 'CERTIFICATE_CREATE'::character varying, 'CERTIFICATE_UPDATE'::character varying, 'CERTIFICATE_DELETE'::character varying, 'EXPERIENCE_READ'::character varying, 'EXPERIENCE_CREATE'::character varying, 'EXPERIENCE_UPDATE'::character varying, 'EXPERIENCE_DELETE'::character varying, 'POST_READ'::character varying, 'POST_READ_BY_ID'::character varying, 'POST_CREATE'::character varying, 'POST_UPDATE'::character varying, 'POST_DELETE'::character varying, 'ADMIN_ACCESS'::character varying])::text[])))
);


--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    post_type character varying(255) NOT NULL,
    vacancy_status character varying(255),
    CONSTRAINT post_post_type_check CHECK (((post_type)::text = ANY ((ARRAY['PUBLICATION'::character varying, 'VACANCY'::character varying])::text[]))),
    CONSTRAINT post_vacancy_status_check CHECK (((vacancy_status)::text = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'OPEN'::character varying, 'CLOSED'::character varying, 'PAUSED'::character varying, 'ARCHIVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: post_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_file (
    "position" integer,
    file_id bigint,
    id bigint NOT NULL,
    post_id bigint
);


--
-- Name: post_file_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_impression; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_impression (
    interacted boolean NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    post_id bigint,
    seen_at timestamp(6) with time zone NOT NULL,
    user_id bigint
);


--
-- Name: post_impression_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.post_impression ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_impression_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: post_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.post_users (
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    personal_summary character varying(1000),
    banner character varying(255),
    head_line character varying(255),
    locality character varying(255),
    photo character varying(255),
    social_links character varying(255)
);


--
-- Name: profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publication; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.publication (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    body character varying(255),
    title character varying(255)
);


--
-- Name: publication_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.publication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.publication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    permission_id bigint NOT NULL,
    role_id bigint NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255),
    role_name character varying(255),
    CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY ((ARRAY['ADMINISTRATOR'::character varying, 'CANDIDATE'::character varying, 'ENTERPRISE'::character varying, 'MODERATOR'::character varying, 'RECRUITER'::character varying, 'VIEWER'::character varying, 'SUPPORT'::character varying])::text[])))
);


--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sector; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sector (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    title character varying(255)
);


--
-- Name: sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sector ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: selection_process; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.selection_process (
    is_active boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    vacancy_id bigint,
    description character varying(255),
    title character varying(255)
);


--
-- Name: selection_process_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.selection_process ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.selection_process_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: selection_stage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.selection_stage (
    is_required boolean,
    max_score double precision,
    stage_order integer,
    visible boolean NOT NULL,
    weight double precision,
    id bigint NOT NULL,
    vacancy_id bigint NOT NULL,
    analysis_dimension character varying(255),
    name character varying(255),
    stage_type character varying(255),
    url character varying(255),
    CONSTRAINT selection_stage_analysis_dimension_check CHECK (((analysis_dimension)::text = ANY ((ARRAY['REQUIRED_SKILL'::character varying, 'OPTIONAL_SKILL'::character varying, 'TECHNICAL'::character varying, 'BEHAVIORAL'::character varying, 'CERTIFICATES'::character varying, 'EXPERIENCES'::character varying])::text[]))),
    CONSTRAINT selection_stage_stage_type_check CHECK (((stage_type)::text = ANY ((ARRAY['TECHNICAL_TEST'::character varying, 'BEHAVIORAL_TEST'::character varying, 'SKILL_REQUIRED'::character varying, 'SKILL_OPTIONAL'::character varying, 'CERTIFICATE'::character varying, 'EXPERIENCE'::character varying])::text[])))
);


--
-- Name: selection_stage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.selection_stage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.selection_stage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skill_base; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skill_base (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    skill_type character varying(255),
    title character varying(255),
    CONSTRAINT skill_base_skill_type_check CHECK (((skill_type)::text = ANY ((ARRAY['BEHAVIORAL'::character varying, 'TECHNICAL'::character varying])::text[])))
);


--
-- Name: skill_base_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skill_base ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_base_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skill_candidate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skill_candidate (
    candidate_id bigint NOT NULL,
    certificate_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    experience_id bigint,
    id bigint NOT NULL,
    skill_base_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    skill_level character varying(255),
    source character varying(255),
    CONSTRAINT skill_candidate_skill_level_check CHECK (((skill_level)::text = ANY ((ARRAY['BASIC'::character varying, 'INTERMEDIATE'::character varying, 'ADVANCED'::character varying, 'NON_SPECIFIED'::character varying])::text[]))),
    CONSTRAINT skill_candidate_source_check CHECK (((source)::text = ANY ((ARRAY['MANUAL'::character varying, 'CERTIFICATE'::character varying, 'EXPERIENCE'::character varying])::text[])))
);


--
-- Name: skill_candidate_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skill_candidate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_candidate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skill_vacancy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skill_vacancy (
    required boolean,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    skill_base_id bigint,
    updated_at timestamp(6) without time zone,
    vacancy_id bigint
);


--
-- Name: skill_vacancy_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skill_vacancy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skill_vacancy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscription (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    plan character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT subscription_plan_check CHECK (((plan)::text = ANY ((ARRAY['FREE'::character varying, 'PREMIUM'::character varying])::text[]))),
    CONSTRAINT subscription_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_feed_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_feed_config (
    pool_size integer NOT NULL,
    vacancy_lambda double precision NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: user_feed_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_feed_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_feed_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    email character varying(255),
    password character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vacancys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vacancys (
    expiration_date date,
    has_a_behavioral_test boolean,
    has_a_technical_test boolean,
    publication_date date,
    required_certificate boolean,
    closed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    enterprise_id bigint,
    id bigint NOT NULL,
    max_experience_range bigint,
    min_experience_range bigint,
    post_id bigint NOT NULL,
    sector_id bigint,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    experience_range character varying(255),
    locality character varying(255),
    modality_type character varying(255),
    "position" character varying(255),
    title character varying(255),
    vacancy_status character varying(255),
    vacancy_type character varying(255),
    CONSTRAINT vacancys_experience_range_check CHECK (((experience_range)::text = ANY ((ARRAY['ZERO_TO_SIX_MONTHS'::character varying, 'ONE_TO_TWO_YEARS'::character varying, 'TWO_TO_FOUR_YEARS'::character varying, 'FOUR_PLUS_YEARS'::character varying])::text[]))),
    CONSTRAINT vacancys_modality_type_check CHECK (((modality_type)::text = ANY ((ARRAY['ON_SITE'::character varying, 'REMOTE'::character varying, 'HYBRID'::character varying])::text[]))),
    CONSTRAINT vacancys_vacancy_status_check CHECK (((vacancy_status)::text = ANY ((ARRAY['PENDING_APPROVAL'::character varying, 'APPROVED'::character varying, 'OPEN'::character varying, 'CLOSED'::character varying, 'PAUSED'::character varying, 'ARCHIVED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT vacancys_vacancy_type_check CHECK (((vacancy_type)::text = ANY ((ARRAY['FULL_TIME'::character varying, 'PART_TIME'::character varying, 'INTERSHIP'::character varying, 'TRAINEE'::character varying, 'TEMPORARY'::character varying, 'CONTRACT'::character varying, 'FREELANCE'::character varying, 'SELF_EMPLOYED'::character varying, 'VOLUNTEER'::character varying, 'APPRENTICESHIP'::character varying])::text[])))
);


--
-- Name: vacancys_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vacancys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vacancys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: application_analysis; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.application_analysis (final_score, id, job_application_id, compatibility_level, final_feedback) FROM stdin;
\.


--
-- Data for Name: application_analysis_dimension; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.application_analysis_dimension (score, weight, weighted_score, analysis_id, id, selection_stage_id) FROM stdin;
\.


--
-- Data for Name: application_stage_result; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.application_stage_result (locked, score, id, job_application_id, selection_stage_id, stage_status) FROM stdin;
\.


--
-- Data for Name: attachments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.attachments (candidate_id, file_id, id, type) FROM stdin;
\.


--
-- Data for Name: candidate_preferences; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.candidate_preferences (candidate_id, id, total_experience, modality, vacancy_type) FROM stdin;
1	1	0	\N	\N
\.


--
-- Data for Name: candidates; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.candidates (date_of_birth, created_at, id, profile_id, sector_id, updated_at, user_id, availability, contact, cpf, full_name, gender, race_ethnicity) FROM stdin;
\N	2026-04-12 14:57:48.364829	1	1	\N	2026-04-12 14:57:48.364849	1	\N	98999998888	12345678901	Marcelo Cavalcanti	\N	\N
\.


--
-- Data for Name: certificate_sectors; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.certificate_sectors (certificate_id, sector_id) FROM stdin;
\.


--
-- Data for Name: certificates; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.certificates (expiration_date, issue_date, candidate_id, hours, id, issuing_organization, title, url) FROM stdin;
2026-12-01	2026-01-01	1	50	1	ANBIMA	CPRO-R	
\.


--
-- Data for Name: enterprises; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.enterprises (is_approved, size_enterprise, created_at, id, number_of_employees, profile_id, updated_at, user_id, cnpj, contact, description, enterprise_name, sector, site_url, social_reason) FROM stdin;
f	\N	2026-04-12 14:57:55.672772	1	\N	2	2026-04-12 14:57:55.681107	2	40415388000194	98999999999	\N	Freires & Cavalcanti LTDA	\N	\N	\N
\.


--
-- Data for Name: experiences; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.experiences (end_date, is_current, start_date, candidate_id, id, description, locality, organization, title, work_modality, work_type) FROM stdin;
\.


--
-- Data for Name: feed_item_score; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.feed_item_score (score, created_at, id, post_id, updated_at) FROM stdin;
\.


--
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.files (id, size, content_type, file_name, media_type, path) FROM stdin;
\.


--
-- Data for Name: interaction; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.interaction (id, post_impression_id) FROM stdin;
\.


--
-- Data for Name: job_application; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.job_application (candidate_id, id, vacancy_id, status) FROM stdin;
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.permissions (id, permission_name) FROM stdin;
1	PROFILE_READ
2	PROFILE_READ_BY_ID
3	PROFILE_READ_DETAILS
4	PROFILE_UPDATE
5	CANDIDATE_READ
6	CANDIDATE_READ_BY_ID
7	CANDIDATE_READ_DETAILS
8	ENTERPRISE_READ
9	ENTERPRISE_READ_BY_ID
10	ENTERPRISE_READ_DETAILS
11	USER_READ
12	USER_READ_BY_ID
13	USER_READ_DETAILS
14	VACANCY_READ
15	VACANCY_READ_BY_ID
16	VACANCY_READ_DETAILS
17	VACANCY_CREATE
18	VACANCY_UPDATE
19	JOB_APPLICATION_READ
20	JOB_APPLICATION_READ_BY_ID
21	JOB_APPLICATION_READ_DETAILS
22	JOB_APPLICATION_APPLY
23	SELECTION_PROCESS_READ
24	SELECTION_PROCESS_READ_BY_ID
25	SELECTION_PROCESS_READ_DETAILS
26	SKILL_READ
27	SKILL_CREATE
28	SKILL_UPDATE
29	CERTIFICATE_READ
30	CERTIFICATE_CREATE
31	CERTIFICATE_UPDATE
32	CERTIFICATE_DELETE
33	EXPERIENCE_READ
34	EXPERIENCE_CREATE
35	EXPERIENCE_UPDATE
36	EXPERIENCE_DELETE
37	POST_READ
38	POST_READ_BY_ID
39	POST_CREATE
40	POST_UPDATE
41	POST_DELETE
42	ADMIN_ACCESS
\.


--
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.post (created_at, id, updated_at, post_type, vacancy_status) FROM stdin;
\.


--
-- Data for Name: post_file; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.post_file ("position", file_id, id, post_id) FROM stdin;
\.


--
-- Data for Name: post_impression; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.post_impression (interacted, expires_at, id, post_id, seen_at, user_id) FROM stdin;
\.


--
-- Data for Name: post_users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.post_users (post_id, user_id) FROM stdin;
\.


--
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.profile (created_at, id, updated_at, personal_summary, banner, head_line, locality, photo, social_links) FROM stdin;
2026-04-12 14:57:55.665386	2	2026-04-12 14:57:55.665406	\N	\N	\N	\N	\N	\N
2026-04-12 14:57:48.34722	1	2026-04-13 16:26:39.734454	Sou um profissional dedicado à tecnologia, com foco em desenvolvimento de software e soluções eficientes. Busco constantemente aprimorar minhas habilidades e criar sistemas que gerem valor real.	\N	\N	\N	\N	\N
\.


--
-- Data for Name: publication; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.publication (id, post_id, body, title) FROM stdin;
\.


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.role_permissions (permission_id, role_id) FROM stdin;
1	9
2	9
3	9
5	9
6	9
7	9
8	9
9	9
10	9
14	9
15	9
16	9
17	9
18	9
19	9
20	9
21	9
26	9
36	9
37	9
38	9
39	9
40	9
41	9
1	8
2	8
3	8
4	8
5	8
6	8
7	8
8	8
9	8
10	8
11	8
12	8
13	8
14	8
15	8
16	8
18	8
19	8
20	8
21	8
23	8
24	8
25	8
26	8
27	8
28	8
29	8
31	8
32	8
33	8
35	8
36	8
37	8
38	8
40	8
41	8
1	10
2	10
8	10
9	10
14	10
15	10
26	10
37	10
38	10
1	11
2	11
3	11
5	11
6	11
7	11
8	11
9	11
10	11
11	11
12	11
13	11
14	11
15	11
16	11
19	11
20	11
21	11
23	11
24	11
25	11
26	11
29	11
33	11
37	11
38	11
1	13
2	13
3	13
4	13
5	13
6	13
8	13
9	13
10	13
14	13
15	13
16	13
19	13
20	13
21	13
22	13
23	13
24	13
25	13
26	13
27	13
28	13
29	13
30	13
31	13
32	13
33	13
34	13
35	13
36	13
37	13
38	13
1	14
2	14
3	14
5	14
6	14
7	14
8	14
9	14
10	14
14	14
15	14
16	14
17	14
18	14
19	14
20	14
21	14
23	14
24	14
25	14
26	14
29	14
37	14
38	14
39	14
40	14
41	14
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.roles (created_at, id, updated_at, description, name, role_name) FROM stdin;
2026-04-12 14:49:17.263411	8	2026-04-12 14:49:17.263411	Administrador da plataforma. Gerencia usuários, conteúdos e configurações gerais. Pode remover perfis, resolver conflitos e garantir que as regras da plataforma sejam seguidas.	Moderador	MODERATOR
2026-04-12 14:49:17.263411	9	2026-04-12 14:49:17.263411	Empresa ou profissional de RH cadastrado na plataforma. Pode buscar e visualizar perfis de talentos, entrar em contato com candidatos e gerenciar seus processos seletivos.	Recrutador	RECRUITER
2026-04-12 14:49:17.263411	10	2026-04-12 14:49:17.263411	Usuário com acesso de leitura. Pode navegar e visualizar perfis públicos da plataforma, mas sem interagir ou entrar em contato com talentos diretamente.	Leitor	VIEWER
2026-04-12 14:49:17.263411	11	2026-04-12 14:49:17.263411	Equipe de suporte da plataforma. Auxilia usuários com dúvidas e problemas técnicos, podendo acessar informações necessárias para resolver chamados, sem permissão de alterar dados sensíveis.	Suporte	SUPPORT
2026-04-12 14:49:17.263411	12	2026-04-12 14:49:17.263411	Superusuário da plataforma com acesso total. Gerencia configurações globais, permissões de outros usuários, integrações e dados sensíveis do sistema. Nível mais alto de privilégio.	Administrador	ADMINISTRATOR
2026-04-12 14:49:17.263411	13	2026-04-12 14:49:17.263411	Talento cadastrado na plataforma. Cria e gerencia seu próprio perfil profissional, adiciona experiências, habilidades e portfólio, e pode ser encontrado e contactado por recrutadores.	Candidato	CANDIDATE
2026-04-12 14:49:17.263411	14	2026-04-12 14:49:17.263411	Organização cadastrada na plataforma. Gerencia seu perfil corporativo, publica vagas e tem acesso ao banco de talentos para buscar candidatos alinhados às suas necessidades.	Empresa	ENTERPRISE
\.


--
-- Data for Name: sector; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sector (created_at, id, updated_at, title) FROM stdin;
2026-04-13 16:32:13.95329	1	2026-04-13 16:32:13.95329	Renda Variável
2026-04-13 16:32:13.95329	2	2026-04-13 16:32:13.95329	Renda Fixa
2026-04-13 16:32:13.95329	3	2026-04-13 16:32:13.95329	Fundos de Investimento
2026-04-13 16:32:13.95329	4	2026-04-13 16:32:13.95329	Mercado de Capitais
2026-04-13 16:32:13.95329	5	2026-04-13 16:32:13.95329	Private Equity e Venture Capital
2026-04-13 16:32:13.95329	6	2026-04-13 16:32:13.95329	Gestão de Ativos (Asset Management)
2026-04-13 16:32:13.95329	7	2026-04-13 16:32:13.95329	Banco de Investimento (Investment Banking)
2026-04-13 16:32:13.95329	8	2026-04-13 16:32:13.95329	Tesouraria Corporativa
2026-04-13 16:32:13.95329	9	2026-04-13 16:32:13.95329	Seguros e Resseguros
2026-04-13 16:32:13.95329	10	2026-04-13 16:32:13.95329	Fintechs e Serviços Financeiros Digitais
\.


--
-- Data for Name: selection_process; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.selection_process (is_active, created_at, id, updated_at, vacancy_id, description, title) FROM stdin;
\.


--
-- Data for Name: selection_stage; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.selection_stage (is_required, max_score, stage_order, visible, weight, id, vacancy_id, analysis_dimension, name, stage_type, url) FROM stdin;
\.


--
-- Data for Name: skill_base; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.skill_base (created_at, id, updated_at, skill_type, title) FROM stdin;
2026-04-13 16:31:14.674625	1	2026-04-13 16:31:14.674625	TECHNICAL	Análise fundamentalista de ações
2026-04-13 16:31:14.674625	2	2026-04-13 16:31:14.674625	TECHNICAL	Leitura e interpretação de balanços patrimoniais
2026-04-13 16:31:14.674625	3	2026-04-13 16:31:14.674625	TECHNICAL	Modelagem financeira e valuation (DCF)
2026-04-13 16:31:14.674625	4	2026-04-13 16:31:14.674625	TECHNICAL	Análise técnica e leitura de gráficos
2026-04-13 16:31:14.674625	5	2026-04-13 16:31:14.674625	TECHNICAL	Gestão de risco e sizing de posições
2026-04-13 16:31:14.674625	6	2026-04-13 16:31:14.674625	TECHNICAL	Conhecimento em produtos de renda fixa (CDB, LCI, LCA, Tesouro)
2026-04-13 16:31:14.674625	7	2026-04-13 16:31:14.674625	TECHNICAL	Operação com derivativos (opções, futuros, swaps)
2026-04-13 16:31:14.674625	8	2026-04-13 16:31:14.674625	TECHNICAL	Gestão de carteiras e alocação de ativos
2026-04-13 16:31:14.674625	9	2026-04-13 16:31:14.674625	TECHNICAL	Regulação do mercado financeiro (CVM, BACEN, ANBIMA)
2026-04-13 16:31:14.674625	10	2026-04-13 16:31:14.674625	TECHNICAL	Análise macroeconômica e indicadores (IPCA, SELIC, PIB)
2026-04-13 16:31:14.674625	11	2026-04-13 16:31:14.674625	BEHAVIORAL	Tomada de decisão sob pressão e volatilidade
2026-04-13 16:31:14.674625	12	2026-04-13 16:31:14.674625	BEHAVIORAL	Disciplina e controle emocional em operações
2026-04-13 16:31:14.674625	13	2026-04-13 16:31:14.674625	BEHAVIORAL	Pensamento crítico e ceticismo analítico
2026-04-13 16:31:14.674625	14	2026-04-13 16:31:14.674625	BEHAVIORAL	Orientação a resultados e foco em performance
2026-04-13 16:31:14.674625	15	2026-04-13 16:31:14.674625	BEHAVIORAL	Ética e integridade em ambientes regulados
2026-04-13 16:31:14.674625	16	2026-04-13 16:31:14.674625	BEHAVIORAL	Comunicação clara de teses de investimento
2026-04-13 16:31:14.674625	17	2026-04-13 16:31:14.674625	BEHAVIORAL	Capacidade de aprendizado contínuo e adaptação
2026-04-13 16:31:14.674625	18	2026-04-13 16:31:14.674625	BEHAVIORAL	Gestão de conflitos de interesse e imparcialidade
2026-04-13 16:31:14.674625	19	2026-04-13 16:31:14.674625	BEHAVIORAL	Resiliência frente a perdas e drawdowns
2026-04-13 16:31:14.674625	20	2026-04-13 16:31:14.674625	BEHAVIORAL	Colaboração em comitês de investimento e trabalho em equipe
\.


--
-- Data for Name: skill_candidate; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.skill_candidate (candidate_id, certificate_id, created_at, experience_id, id, skill_base_id, updated_at, skill_level, source) FROM stdin;
\.


--
-- Data for Name: skill_vacancy; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.skill_vacancy (required, created_at, id, skill_base_id, updated_at, vacancy_id) FROM stdin;
\.


--
-- Data for Name: subscription; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.subscription (created_at, id, updated_at, user_id, plan, status) FROM stdin;
2026-04-12 14:57:48.375902	1	2026-04-12 14:57:48.375929	1	FREE	ACTIVE
\.


--
-- Data for Name: user_feed_config; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_feed_config (pool_size, vacancy_lambda, created_at, id, updated_at, user_id) FROM stdin;
10	0.15	2026-04-12 14:57:48.380197	1	2026-04-12 14:57:48.380222	1
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_roles (role_id, user_id) FROM stdin;
13	1
14	2
12	3
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (created_at, id, updated_at, email, password) FROM stdin;
2026-04-12 14:57:48.2742	1	2026-04-12 14:57:48.274489	marcelo.cavalcanti.sousa@gmail.com	$2a$10$5h8YdxVObFIFriftP/L.Oey4Ig.kYIIPa.XuC/gOuCxjbd5cxzomG
2026-04-12 14:57:55.678226	2	2026-04-12 14:57:55.678241	freires&cavalcanti@gmail.com	\N
2026-04-12 14:58:22.713201	3	2026-04-12 14:58:22.713225	raulcruz@ormarcosmaluf.com	$2a$10$WflQHUp0noRkkywvdb9hSej6ZCJJnfQz4KJaMXeWXJ2ic9p2RoRcu
\.


--
-- Data for Name: vacancys; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.vacancys (expiration_date, has_a_behavioral_test, has_a_technical_test, publication_date, required_certificate, closed_at, created_at, enterprise_id, id, max_experience_range, min_experience_range, post_id, sector_id, updated_at, description, experience_range, locality, modality_type, "position", title, vacancy_status, vacancy_type) FROM stdin;
\.


--
-- Name: application_analysis_dimension_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.application_analysis_dimension_id_seq', 1, false);


--
-- Name: application_analysis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.application_analysis_id_seq', 1, false);


--
-- Name: application_stage_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.application_stage_result_id_seq', 1, false);


--
-- Name: attachments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.attachments_id_seq', 1, false);


--
-- Name: candidate_preferences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.candidate_preferences_id_seq', 1, true);


--
-- Name: candidates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.candidates_id_seq', 1, true);


--
-- Name: certificates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.certificates_id_seq', 1, true);


--
-- Name: enterprises_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.enterprises_id_seq', 1, true);


--
-- Name: experiences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.experiences_id_seq', 1, false);


--
-- Name: feed_item_score_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.feed_item_score_id_seq', 1, false);


--
-- Name: files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.files_id_seq', 1, false);


--
-- Name: interaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.interaction_id_seq', 1, false);


--
-- Name: job_application_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.job_application_id_seq', 1, false);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.permissions_id_seq', 42, true);


--
-- Name: post_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.post_file_id_seq', 1, false);


--
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.post_id_seq', 1, false);


--
-- Name: post_impression_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.post_impression_id_seq', 1, false);


--
-- Name: profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.profile_id_seq', 2, true);


--
-- Name: publication_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.publication_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_seq', 14, true);


--
-- Name: sector_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sector_id_seq', 10, true);


--
-- Name: selection_process_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.selection_process_id_seq', 1, false);


--
-- Name: selection_stage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.selection_stage_id_seq', 1, false);


--
-- Name: skill_base_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.skill_base_id_seq', 20, true);


--
-- Name: skill_candidate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.skill_candidate_id_seq', 1, false);


--
-- Name: skill_vacancy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.skill_vacancy_id_seq', 1, false);


--
-- Name: subscription_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.subscription_id_seq', 1, true);


--
-- Name: user_feed_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_feed_config_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- Name: vacancys_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.vacancys_id_seq', 1, false);


--
-- Name: application_analysis_dimension application_analysis_dimension_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis_dimension
    ADD CONSTRAINT application_analysis_dimension_pkey PRIMARY KEY (id);


--
-- Name: application_analysis_dimension application_analysis_dimension_selection_stage_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis_dimension
    ADD CONSTRAINT application_analysis_dimension_selection_stage_id_key UNIQUE (selection_stage_id);


--
-- Name: application_analysis application_analysis_job_application_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis
    ADD CONSTRAINT application_analysis_job_application_id_key UNIQUE (job_application_id);


--
-- Name: application_analysis application_analysis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis
    ADD CONSTRAINT application_analysis_pkey PRIMARY KEY (id);


--
-- Name: application_stage_result application_stage_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_stage_result
    ADD CONSTRAINT application_stage_result_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: candidate_preferences candidate_preferences_candidate_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidate_preferences
    ADD CONSTRAINT candidate_preferences_candidate_id_key UNIQUE (candidate_id);


--
-- Name: candidate_preferences candidate_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidate_preferences
    ADD CONSTRAINT candidate_preferences_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_pkey PRIMARY KEY (id);


--
-- Name: candidates candidates_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_profile_id_key UNIQUE (profile_id);


--
-- Name: candidates candidates_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT candidates_user_id_key UNIQUE (user_id);


--
-- Name: certificate_sectors certificate_sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_sectors
    ADD CONSTRAINT certificate_sectors_pkey PRIMARY KEY (certificate_id, sector_id);


--
-- Name: certificates certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT certificates_pkey PRIMARY KEY (id);


--
-- Name: enterprises enterprises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enterprises
    ADD CONSTRAINT enterprises_pkey PRIMARY KEY (id);


--
-- Name: enterprises enterprises_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enterprises
    ADD CONSTRAINT enterprises_profile_id_key UNIQUE (profile_id);


--
-- Name: enterprises enterprises_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enterprises
    ADD CONSTRAINT enterprises_user_id_key UNIQUE (user_id);


--
-- Name: experiences experiences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT experiences_pkey PRIMARY KEY (id);


--
-- Name: feed_item_score feed_item_score_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_item_score
    ADD CONSTRAINT feed_item_score_pkey PRIMARY KEY (id);


--
-- Name: feed_item_score feed_item_score_post_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_item_score
    ADD CONSTRAINT feed_item_score_post_id_key UNIQUE (post_id);


--
-- Name: files files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);


--
-- Name: interaction interaction_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interaction
    ADD CONSTRAINT interaction_pkey PRIMARY KEY (id);


--
-- Name: job_application job_application_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT job_application_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_permission_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_permission_name_key UNIQUE (permission_name);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: post_file post_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT post_file_pkey PRIMARY KEY (id);


--
-- Name: post_impression post_impression_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_impression
    ADD CONSTRAINT post_impression_pkey PRIMARY KEY (id);


--
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- Name: publication publication_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.publication
    ADD CONSTRAINT publication_pkey PRIMARY KEY (id);


--
-- Name: publication publication_post_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.publication
    ADD CONSTRAINT publication_post_id_key UNIQUE (post_id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (permission_id, role_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: sector sector_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector
    ADD CONSTRAINT sector_pkey PRIMARY KEY (id);


--
-- Name: selection_process selection_process_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.selection_process
    ADD CONSTRAINT selection_process_pkey PRIMARY KEY (id);


--
-- Name: selection_stage selection_stage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.selection_stage
    ADD CONSTRAINT selection_stage_pkey PRIMARY KEY (id);


--
-- Name: skill_base skill_base_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_base
    ADD CONSTRAINT skill_base_pkey PRIMARY KEY (id);


--
-- Name: skill_candidate skill_candidate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_candidate
    ADD CONSTRAINT skill_candidate_pkey PRIMARY KEY (id);


--
-- Name: skill_vacancy skill_vacancy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_vacancy
    ADD CONSTRAINT skill_vacancy_pkey PRIMARY KEY (id);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (id);


--
-- Name: subscription subscription_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_user_id_key UNIQUE (user_id);


--
-- Name: user_feed_config user_feed_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feed_config
    ADD CONSTRAINT user_feed_config_pkey PRIMARY KEY (id);


--
-- Name: user_feed_config user_feed_config_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feed_config
    ADD CONSTRAINT user_feed_config_user_id_key UNIQUE (user_id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: vacancys vacancys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancys
    ADD CONSTRAINT vacancys_pkey PRIMARY KEY (id);


--
-- Name: vacancys vacancys_post_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancys
    ADD CONSTRAINT vacancys_post_id_key UNIQUE (post_id);


--
-- Name: post_impression fk12his5ggy91uq4x38a0xnahyt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_impression
    ADD CONSTRAINT fk12his5ggy91uq4x38a0xnahyt FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: post_users fk1eiaqoq8dyr0ujm3ba7qdk7gp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_users
    ADD CONSTRAINT fk1eiaqoq8dyr0ujm3ba7qdk7gp FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: certificate_sectors fk1fay3bywkhftba1sam70gdupa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_sectors
    ADD CONSTRAINT fk1fay3bywkhftba1sam70gdupa FOREIGN KEY (certificate_id) REFERENCES public.certificates(id);


--
-- Name: vacancys fk3h7n9q8kgli5x2ybrls7hdbku; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancys
    ADD CONSTRAINT fk3h7n9q8kgli5x2ybrls7hdbku FOREIGN KEY (sector_id) REFERENCES public.sector(id);


--
-- Name: skill_candidate fk451x2pw5dkbn80bmrpd40eobn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_candidate
    ADD CONSTRAINT fk451x2pw5dkbn80bmrpd40eobn FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: user_feed_config fk47ow3g9ij02fmhvjfu116akad; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feed_config
    ADD CONSTRAINT fk47ow3g9ij02fmhvjfu116akad FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: skill_candidate fk4rs7fox1dvay3k6qft96i481j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_candidate
    ADD CONSTRAINT fk4rs7fox1dvay3k6qft96i481j FOREIGN KEY (skill_base_id) REFERENCES public.skill_base(id);


--
-- Name: application_analysis_dimension fk4ygpsy78j37jekam659r544n7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis_dimension
    ADD CONSTRAINT fk4ygpsy78j37jekam659r544n7 FOREIGN KEY (selection_stage_id) REFERENCES public.selection_stage(id);


--
-- Name: experiences fk5pts9l4acfs3e1h5u3y35sudc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.experiences
    ADD CONSTRAINT fk5pts9l4acfs3e1h5u3y35sudc FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: application_analysis_dimension fk7lc9fuveca89001wjgswy0tkw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis_dimension
    ADD CONSTRAINT fk7lc9fuveca89001wjgswy0tkw FOREIGN KEY (analysis_id) REFERENCES public.application_analysis(id);


--
-- Name: application_analysis fk7rtrps12o363nkhx89ju0ek1b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_analysis
    ADD CONSTRAINT fk7rtrps12o363nkhx89ju0ek1b FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: certificate_sectors fk80kbng06eb1j6y9551ujyt6tv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificate_sectors
    ADD CONSTRAINT fk80kbng06eb1j6y9551ujyt6tv FOREIGN KEY (sector_id) REFERENCES public.sector(id);


--
-- Name: interaction fk9o9804faqto1a3v8yv15j14o0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interaction
    ADD CONSTRAINT fk9o9804faqto1a3v8yv15j14o0 FOREIGN KEY (post_impression_id) REFERENCES public.post_impression(id);


--
-- Name: post_file fkby494sknmp6km80i0t0bc82gb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT fkby494sknmp6km80i0t0bc82gb FOREIGN KEY (file_id) REFERENCES public.files(id);


--
-- Name: candidate_preferences fkcn6lkmc1r6hnerpyxmci0kn38; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidate_preferences
    ADD CONSTRAINT fkcn6lkmc1r6hnerpyxmci0kn38 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: vacancys fkcwbp1j2b9c26riyyjxprsmetx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancys
    ADD CONSTRAINT fkcwbp1j2b9c26riyyjxprsmetx FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: role_permissions fkegdk29eiy7mdtefy5c7eirr6e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkegdk29eiy7mdtefy5c7eirr6e FOREIGN KEY (permission_id) REFERENCES public.permissions(id);


--
-- Name: selection_stage fkf1aaqsidd3ap08ol9igx14wmp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.selection_stage
    ADD CONSTRAINT fkf1aaqsidd3ap08ol9igx14wmp FOREIGN KEY (vacancy_id) REFERENCES public.vacancys(id);


--
-- Name: skill_candidate fkfas865y9rk3s4nlvsm01p3uer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_candidate
    ADD CONSTRAINT fkfas865y9rk3s4nlvsm01p3uer FOREIGN KEY (certificate_id) REFERENCES public.certificates(id);


--
-- Name: skill_vacancy fkg30ghng7o69kibrwo42ucf8ge; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_vacancy
    ADD CONSTRAINT fkg30ghng7o69kibrwo42ucf8ge FOREIGN KEY (vacancy_id) REFERENCES public.vacancys(id);


--
-- Name: enterprises fkgwhwka4fieky5ubej703irgnv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enterprises
    ADD CONSTRAINT fkgwhwka4fieky5ubej703irgnv FOREIGN KEY (profile_id) REFERENCES public.profile(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: attachments fkh9io9v0megiiy1am1p0by1mak; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fkh9io9v0megiiy1am1p0by1mak FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: job_application fkh9wg68ilb7hmn2ya9mfaaw4h7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fkh9wg68ilb7hmn2ya9mfaaw4h7 FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: publication fkhdnec6b77ygxs34st111q1uji; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.publication
    ADD CONSTRAINT fkhdnec6b77ygxs34st111q1uji FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: post_impression fkhfle1m7fmosnk1cxoptafhg7e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_impression
    ADD CONSTRAINT fkhfle1m7fmosnk1cxoptafhg7e FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: job_application fki2539f7afnd9xbd3w9jixspn2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.job_application
    ADD CONSTRAINT fki2539f7afnd9xbd3w9jixspn2 FOREIGN KEY (vacancy_id) REFERENCES public.vacancys(id);


--
-- Name: candidates fkm216ns4754viej0mmvbia3x0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fkm216ns4754viej0mmvbia3x0y FOREIGN KEY (profile_id) REFERENCES public.profile(id);


--
-- Name: candidates fkme4fkelukmx2s63tlcrft6hio; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fkme4fkelukmx2s63tlcrft6hio FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: role_permissions fkn5fotdgk8d1xvo8nav9uv3muc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fkn5fotdgk8d1xvo8nav9uv3muc FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: post_file fkn75omflablcagq3jsuoognqwy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_file
    ADD CONSTRAINT fkn75omflablcagq3jsuoognqwy FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: feed_item_score fknpk8rpwud68if9kf1pextgtn4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feed_item_score
    ADD CONSTRAINT fknpk8rpwud68if9kf1pextgtn4 FOREIGN KEY (post_id) REFERENCES public.post(id);


--
-- Name: skill_candidate fko22j8gml1ttayim71gv98pl1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_candidate
    ADD CONSTRAINT fko22j8gml1ttayim71gv98pl1 FOREIGN KEY (experience_id) REFERENCES public.experiences(id);


--
-- Name: application_stage_result fkomd2qk2nis50ibatcgpg6ypk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_stage_result
    ADD CONSTRAINT fkomd2qk2nis50ibatcgpg6ypk FOREIGN KEY (job_application_id) REFERENCES public.job_application(id);


--
-- Name: skill_vacancy fkox3nm4wegle95i5vsid9vqbpb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skill_vacancy
    ADD CONSTRAINT fkox3nm4wegle95i5vsid9vqbpb FOREIGN KEY (skill_base_id) REFERENCES public.skill_base(id);


--
-- Name: selection_process fkpfc8vrun7ukmtsg914lqm8ugv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.selection_process
    ADD CONSTRAINT fkpfc8vrun7ukmtsg914lqm8ugv FOREIGN KEY (vacancy_id) REFERENCES public.vacancys(id);


--
-- Name: post_users fkpu0bfvwu4b5u6dhirreyuejxu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.post_users
    ADD CONSTRAINT fkpu0bfvwu4b5u6dhirreyuejxu FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: application_stage_result fkq9g8c7nyvu9ugf97wyjd876fh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_stage_result
    ADD CONSTRAINT fkq9g8c7nyvu9ugf97wyjd876fh FOREIGN KEY (selection_stage_id) REFERENCES public.selection_stage(id);


--
-- Name: subscription fkqwd9pkhbsmapx9poug5wnnpkc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkqwd9pkhbsmapx9poug5wnnpkc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: candidates fkr5qvor849ych7eow0th4mq5u6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candidates
    ADD CONSTRAINT fkr5qvor849ych7eow0th4mq5u6 FOREIGN KEY (sector_id) REFERENCES public.sector(id);


--
-- Name: vacancys fkrx14df5m2mq33fydxjojg85b8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vacancys
    ADD CONSTRAINT fkrx14df5m2mq33fydxjojg85b8 FOREIGN KEY (enterprise_id) REFERENCES public.enterprises(id);


--
-- Name: attachments fksmrevr8b9202m113f0sdda24d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT fksmrevr8b9202m113f0sdda24d FOREIGN KEY (file_id) REFERENCES public.files(id);


--
-- Name: certificates fkt8r0o54nmp2jussm9qm3xedvu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.certificates
    ADD CONSTRAINT fkt8r0o54nmp2jussm9qm3xedvu FOREIGN KEY (candidate_id) REFERENCES public.candidates(id);


--
-- Name: enterprises fktegoe6oujp8lc23w368lii1i4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enterprises
    ADD CONSTRAINT fktegoe6oujp8lc23w368lii1i4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict kGWHK2nj6pumHsEYunCa2zAuxEb6JwiZkUDlNte1gNR4WL8D0V89BvXgDR2hDzC

